### ISSUE TITLE
A way to make all commands use the same set of guild IDs

### ISSUE THREAD

**Issue by Artemis21** [starsflower/discordpy-slash-commands#1]
Often I'm making a bot for a single guild, so all my commands will be just for that guild. Passing `guild_ids` with every command registered would not be ideal, I'd rather just be able to pass it on the `SlashCommand` initialiser and have it used by default on all commands.

Is this possible?

**Comment by mwja** [comment]
Definitely possible. I'll take a look and make it work for the next release 👍

**Comment by mwja** [comment]
Got this prepped for release/1.2.2. Hopefully that'll be done within a day, I'll give you a mention when it's there 😉

**Comment by mwja** [comment]
https://pypi.org/project/dpyslash/1.2.2/ Here ya go ! @Artemis21. Pass `guild_ids` to `SlashCommand` the same way you'd pass it to a function 😉

**Comment by Artemis21** [comment]
Looks cool! I ended up re-maintaing my own wrapper for this project, but I imagine this would be useful even for testing normal multi-server bots during development.
